curl 'https://www.wtrl.racing/api/wtrlruby/?wtrlid=ttt&season=299&action=results&_=1736965584307' \
  -H 'accept: application/json, text/javascript, */*; q=0.01' \
  -H 'accept-language: en-CA,en-GB;q=0.9,en-US;q=0.8,en;q=0.7' \
  -H 'access-control-allow-credentials: true' \
  -H 'access-control-allow-headers: Accept' \
  -H 'access-control-allow-origin: https://www.wtrl.racing' \
  -H 'authorization: Bearer undefined' \
  -H 'cache-control: no-cache' \
  -H 'cookie: _ga=GA1.1.141107064.1725975784; wtrl_sid=xxx; wtrl_ouid=xxx; _ga_SL0YM0MYT3=GS1.1.1736965493.37.1.1736965583.0.0.0' \
  -H 'pragma: no-cache' \
  -H 'priority: u=1, i' \
  -H 'referer: https://www.wtrl.racing/ttt-results/' \
  -H 'sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36' \
  -H 'wtrl-api-version: 2.7' \
  -H 'wtrl-integrity: xxx' \
  -H 'x-requested-with: XMLHttpRequest'
