from wtrl_ttt_scraper.models import Rider, Team

Team(
    riders=[
        Rider(
            team_rank=0,
            rider_rank=2,
            rider_name="Gaelen Merritt",
            rider_position=None,
            team_name="Waterloo Cycling Club",
            wkg=4.572,
            power=300,
            completed_laps=1,
            total_time=2458.983,
            time_gap=0.036,
            avg_speed=46.854,
            distance=7495,
        ),
        Rider(
            team_rank=0,
            rider_rank=7,
            rider_name="Michael De Borger - WCC",
            rider_position=None,
            team_name="Waterloo Cycling Club",
            wkg=3.813,
            power=292,
            completed_laps=1,
            total_time=2550.164,
            time_gap=91.217,
            avg_speed=45.179,
            distance=605745,
        ),
        Rider(
            team_rank=0,
            rider_rank=1,
            rider_name="Andrew Lambert | WCC",
            rider_position=None,
            team_name="Waterloo Cycling Club",
            wkg=4.845,
            power=291,
            completed_laps=1,
            total_time=2458.947,
            time_gap=0,
            avg_speed=46.855,
            distance=2297202,
        ),
        Rider(
            team_rank=0,
            rider_rank=3,
            rider_name="Eric Reid",
            rider_position=None,
            team_name="Waterloo Cycling Club",
            wkg=3.882,
            power=323,
            completed_laps=1,
            total_time=2459.067,
            time_gap=0.12,
            avg_speed=46.853,
            distance=3646908,
        ),
        Rider(
            team_rank=1,
            rider_rank=4,
            rider_name="Erik Kalviainen",
            rider_position=None,
            team_name="Waterloo Cycling Club",
            wkg=4.112,
            power=317,
            completed_laps=1,
            total_time=2459.083,
            time_gap=0.136,
            avg_speed=46.851,
            distance=4097190,
        ),
        Rider(
            team_rank=0,
            rider_rank=5,
            rider_name="David Kalviainen",
            rider_position=None,
            team_name="Waterloo Cycling Club",
            wkg=3.8,
            power=295,
            completed_laps=1,
            total_time=2479.005,
            time_gap=20.058,
            avg_speed=46.476,
            distance=4707779,
        ),
        Rider(
            team_rank=0,
            rider_rank=6,
            rider_name="Jamie Wagler | WCC",
            rider_position=None,
            team_name="Waterloo Cycling Club",
            wkg=3.995,
            power=307,
            completed_laps=1,
            total_time=2547.741,
            time_gap=88.794,
            avg_speed=45.222,
            distance=5216747,
        ),
    ],
    rank=31,
    total_distance=165.112,
    total_power=81.87,
    zone=27,
    dropped_riders=0,
    coffee_class="Espresso",
    team_time=2459.083,
    lap_count=1,
    avg_speed=46.85,
    total_tss=562,
    total_if=1171,
    total_np=1794,
    team_name="Waterloo Ones",
    rider_count=7,
    completed=0,
    total_time_calc=2459.083,
)
